title: "내 개발 블로그"
remote_theme: kitian616/jekyll-TeXt-theme
baseurl: "/my-blog"

text_skin: default   # default, dark, forest, ocean, chocolate, orange 중 선택

highlight_theme: tomorrow-night-eighties

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap